version: "3.9"

services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
  postgres:
      image: postgres:16.0-alpine3.18
      environment:
          POSTGRES_PASSWORD: postgresql
